/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 12.3.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.api;

import com.questetra.bpms.client.swagger.ApiException;
import com.questetra.bpms.client.swagger.model.ItemCache;
import com.questetra.bpms.client.swagger.model.ItemCacheList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemCacheApi
 */
@Ignore
public class ItemCacheApiTest {

    private final ItemCacheApi api = new ItemCacheApi();

    
    /**
     * Clearing Cached Choices master
     *
     * Clearing Cached Choices master
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteItemCacheTest() throws ApiException {
        String url = null;
        api.deleteItemCache(url);

        // TODO: test validations
    }
    
    /**
     * Retrieving a List of Cached Choices
     *
     * Retrieving a List of Cached Choices
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemCacheTest() throws ApiException {
        String url = null;
        ItemCache response = api.getItemCache(url);

        // TODO: test validations
    }
    
    /**
     * Retrieving a List of Cached Choices master
     *
     * Retrieving a List of Cached Choices master
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listItemCachesTest() throws ApiException {
        ItemCacheList response = api.listItemCaches();

        // TODO: test validations
    }
    
}
