/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.api;

import com.questetra.bpms.client.swagger.ApiException;
import com.questetra.bpms.client.swagger.model.ActivityList;
import com.questetra.bpms.client.swagger.model.Errors;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessModelApi
 */
@Ignore
public class ProcessModelApiTest {

    private final ProcessModelApi api = new ProcessModelApi();

    
    /**
     * Retrieving a List of startable Workflows
     *
     * Retrieving a List of startable Workflows
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStartableProcessModelTest() throws ApiException {
        Integer limit = null;
        Integer start = null;
        String category = null;
        String query = null;
        ActivityList response = api.listStartableProcessModel(limit, start, category, query);

        // TODO: test validations
    }
    
}
