/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.api;

import com.questetra.bpms.client.swagger.ApiException;
import com.questetra.bpms.client.swagger.model.Errors;
import com.questetra.bpms.client.swagger.model.QroleList;
import com.questetra.bpms.client.swagger.model.QroleWrapper;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QroleApi
 */
@Ignore
public class QroleApiTest {

    private final QroleApi api = new QroleApi();

    
    /**
     * Creating a Role Unit
     *
     * Creating a Role Unit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTest() throws ApiException {
        String name = null;
        QroleWrapper response = api.add(name);

        // TODO: test validations
    }
    
    /**
     * Deleting a Role Unit
     *
     * Deleting a Role Unit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        Long id = null;
        api.delete(id);

        // TODO: test validations
    }
    
    /**
     * Retrieving a Role Unit
     *
     * Retrieving a Role Unit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findTest() throws ApiException {
        Integer id = null;
        String name = null;
        QroleWrapper response = api.find(id, name);

        // TODO: test validations
    }
    
    /**
     * Retrieving a List of Roles
     *
     * Retrieving a List of Roles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        String query = null;
        Integer limit = null;
        Integer start = null;
        QroleList response = api.list(query, limit, start);

        // TODO: test validations
    }
    
    /**
     * Updating a Role Unit
     *
     * Updating a Role Unit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        Long id = null;
        String name = null;
        QroleWrapper response = api.update(id, name);

        // TODO: test validations
    }
    
}
