/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.api;

import com.questetra.bpms.client.swagger.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkitemFormApi
 */
@Ignore
public class WorkitemFormApiTest {

    private final WorkitemFormApi api = new WorkitemFormApi();

    
    /**
     * Submitting the Task output
     *
     * Submitting the Task output
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveTest() throws ApiException {
        Long workitemId = null;
        String title = null;
        Long qgroupId = null;
        Long flow = null;
        Boolean saveOnly = null;
        String response = api.save(workitemId, title, qgroupId, flow, saveOnly);

        // TODO: test validations
    }
    
    /**
     * Retrieving a List of forms for Task output
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void viewXmlTest() throws ApiException {
        Long workitemId = null;
        String response = api.viewXml(workitemId);

        // TODO: test validations
    }
    
}
