/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.questetra.bpms.client.swagger.model.ProcessAuthority;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProcessAuthorityWrapper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-01T00:57:19.411Z")
public class ProcessAuthorityWrapper {
  @SerializedName("ProcessAuthority")
  private ProcessAuthority processAuthority = null;

  public ProcessAuthorityWrapper processAuthority(ProcessAuthority processAuthority) {
    this.processAuthority = processAuthority;
    return this;
  }

   /**
   * Get processAuthority
   * @return processAuthority
  **/
  @ApiModelProperty(value = "")
  public ProcessAuthority getProcessAuthority() {
    return processAuthority;
  }

  public void setProcessAuthority(ProcessAuthority processAuthority) {
    this.processAuthority = processAuthority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessAuthorityWrapper processAuthorityWrapper = (ProcessAuthorityWrapper) o;
    return Objects.equals(this.processAuthority, processAuthorityWrapper.processAuthority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processAuthority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessAuthorityWrapper {\n");
    
    sb.append("    processAuthority: ").append(toIndentedString(processAuthority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

