/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 11.7.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.questetra.bpms.client.swagger.model.ProcessModelInfo;
import com.questetra.bpms.client.swagger.model.Qgroup;
import com.questetra.bpms.client.swagger.model.Qrole;
import com.questetra.bpms.client.swagger.model.Quser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProcessAuthority
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-29T16:27:26.082+09:00")
public class ProcessAuthority {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("processModelInfo")
  private ProcessModelInfo processModelInfo = null;

  @SerializedName("type")
  private Integer type = null;

  @SerializedName("quser")
  private Quser quser = null;

  @SerializedName("qgroup")
  private Qgroup qgroup = null;

  @SerializedName("leader")
  private Boolean leader = null;

  @SerializedName("descendantQgroups")
  private Boolean descendantQgroups = null;

  @SerializedName("qrole")
  private Qrole qrole = null;

  public ProcessAuthority id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Process Authorization ID
   * @return id
  **/
  @ApiModelProperty(value = "Process Authorization ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProcessAuthority processModelInfo(ProcessModelInfo processModelInfo) {
    this.processModelInfo = processModelInfo;
    return this;
  }

   /**
   * Get processModelInfo
   * @return processModelInfo
  **/
  @ApiModelProperty(value = "")
  public ProcessModelInfo getProcessModelInfo() {
    return processModelInfo;
  }

  public void setProcessModelInfo(ProcessModelInfo processModelInfo) {
    this.processModelInfo = processModelInfo;
  }

  public ProcessAuthority type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Type of Process Authorization 0:App Administrator Authorization 1:Process Manager Authorization 2:Data Viewer Authorization 3:Data Viewer Authorization(only Progress Information)
   * @return type
  **/
  @ApiModelProperty(value = "Type of Process Authorization 0:App Administrator Authorization 1:Process Manager Authorization 2:Data Viewer Authorization 3:Data Viewer Authorization(only Progress Information)")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public ProcessAuthority quser(Quser quser) {
    this.quser = quser;
    return this;
  }

   /**
   * Get quser
   * @return quser
  **/
  @ApiModelProperty(value = "")
  public Quser getQuser() {
    return quser;
  }

  public void setQuser(Quser quser) {
    this.quser = quser;
  }

  public ProcessAuthority qgroup(Qgroup qgroup) {
    this.qgroup = qgroup;
    return this;
  }

   /**
   * Get qgroup
   * @return qgroup
  **/
  @ApiModelProperty(value = "")
  public Qgroup getQgroup() {
    return qgroup;
  }

  public void setQgroup(Qgroup qgroup) {
    this.qgroup = qgroup;
  }

  public ProcessAuthority leader(Boolean leader) {
    this.leader = leader;
    return this;
  }

   /**
   * 
   * @return leader
  **/
  @ApiModelProperty(value = "")
  public Boolean getLeader() {
    return leader;
  }

  public void setLeader(Boolean leader) {
    this.leader = leader;
  }

  public ProcessAuthority descendantQgroups(Boolean descendantQgroups) {
    this.descendantQgroups = descendantQgroups;
    return this;
  }

   /**
   * 
   * @return descendantQgroups
  **/
  @ApiModelProperty(value = "")
  public Boolean getDescendantQgroups() {
    return descendantQgroups;
  }

  public void setDescendantQgroups(Boolean descendantQgroups) {
    this.descendantQgroups = descendantQgroups;
  }

  public ProcessAuthority qrole(Qrole qrole) {
    this.qrole = qrole;
    return this;
  }

   /**
   * Get qrole
   * @return qrole
  **/
  @ApiModelProperty(value = "")
  public Qrole getQrole() {
    return qrole;
  }

  public void setQrole(Qrole qrole) {
    this.qrole = qrole;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessAuthority processAuthority = (ProcessAuthority) o;
    return Objects.equals(this.id, processAuthority.id) &&
        Objects.equals(this.processModelInfo, processAuthority.processModelInfo) &&
        Objects.equals(this.type, processAuthority.type) &&
        Objects.equals(this.quser, processAuthority.quser) &&
        Objects.equals(this.qgroup, processAuthority.qgroup) &&
        Objects.equals(this.leader, processAuthority.leader) &&
        Objects.equals(this.descendantQgroups, processAuthority.descendantQgroups) &&
        Objects.equals(this.qrole, processAuthority.qrole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, processModelInfo, type, quser, qgroup, leader, descendantQgroups, qrole);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessAuthority {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processModelInfo: ").append(toIndentedString(processModelInfo)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    quser: ").append(toIndentedString(quser)).append("\n");
    sb.append("    qgroup: ").append(toIndentedString(qgroup)).append("\n");
    sb.append("    leader: ").append(toIndentedString(leader)).append("\n");
    sb.append("    descendantQgroups: ").append(toIndentedString(descendantQgroups)).append("\n");
    sb.append("    qrole: ").append(toIndentedString(qrole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

