/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 12.3.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WorkitemFormExecutingrolesExecutingrole
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-13T15:44:52.325+09:00")
public class WorkitemFormExecutingrolesExecutingrole {
  @SerializedName("qgroup-id")
  private Integer qgroupId = null;

  @SerializedName("qgroup-name")
  private String qgroupName = null;

  public WorkitemFormExecutingrolesExecutingrole qgroupId(Integer qgroupId) {
    this.qgroupId = qgroupId;
    return this;
  }

   /**
   * Organazation IDs available
   * @return qgroupId
  **/
  @ApiModelProperty(value = "Organazation IDs available")
  public Integer getQgroupId() {
    return qgroupId;
  }

  public void setQgroupId(Integer qgroupId) {
    this.qgroupId = qgroupId;
  }

  public WorkitemFormExecutingrolesExecutingrole qgroupName(String qgroupName) {
    this.qgroupName = qgroupName;
    return this;
  }

   /**
   * Organazation names available
   * @return qgroupName
  **/
  @ApiModelProperty(value = "Organazation names available")
  public String getQgroupName() {
    return qgroupName;
  }

  public void setQgroupName(String qgroupName) {
    this.qgroupName = qgroupName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkitemFormExecutingrolesExecutingrole workitemFormExecutingrolesExecutingrole = (WorkitemFormExecutingrolesExecutingrole) o;
    return Objects.equals(this.qgroupId, workitemFormExecutingrolesExecutingrole.qgroupId) &&
        Objects.equals(this.qgroupName, workitemFormExecutingrolesExecutingrole.qgroupName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qgroupId, qgroupName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkitemFormExecutingrolesExecutingrole {\n");
    
    sb.append("    qgroupId: ").append(toIndentedString(qgroupId)).append("\n");
    sb.append("    qgroupName: ").append(toIndentedString(qgroupName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

