/*
 * Questetra BPM Suite APIs
 * Questetra BPM Suite APIs
 *
 * OpenAPI spec version: 12.3.0
 * Contact: support@questetra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.questetra.bpms.client.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.questetra.bpms.client.swagger.model.WorkitemFormUserselectsUserselect;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Submit buttons for downstream flows
 */
@ApiModel(description = "Submit buttons for downstream flows")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-13T11:09:14.859+09:00")
public class WorkitemFormUserselects {
  @SerializedName("user-select")
  private List<WorkitemFormUserselectsUserselect> userSelect = null;

  public WorkitemFormUserselects userSelect(List<WorkitemFormUserselectsUserselect> userSelect) {
    this.userSelect = userSelect;
    return this;
  }

  public WorkitemFormUserselects addUserSelectItem(WorkitemFormUserselectsUserselect userSelectItem) {
    if (this.userSelect == null) {
      this.userSelect = new ArrayList<WorkitemFormUserselectsUserselect>();
    }
    this.userSelect.add(userSelectItem);
    return this;
  }

   /**
   * Each submit button for downstream flow
   * @return userSelect
  **/
  @ApiModelProperty(value = "Each submit button for downstream flow")
  public List<WorkitemFormUserselectsUserselect> getUserSelect() {
    return userSelect;
  }

  public void setUserSelect(List<WorkitemFormUserselectsUserselect> userSelect) {
    this.userSelect = userSelect;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkitemFormUserselects workitemFormUserselects = (WorkitemFormUserselects) o;
    return Objects.equals(this.userSelect, workitemFormUserselects.userSelect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userSelect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkitemFormUserselects {\n");
    
    sb.append("    userSelect: ").append(toIndentedString(userSelect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

